In [3]:
import pandas as pd

In [4]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/'
url = f'{prefix}/taxi_zone_lookup.csv'

# https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

In [5]:
df = pd.read_csv(url)

In [6]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [7]:
len(df)

265

In [8]:
df.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [9]:
dtype = {
    "LocationID": "Int64",
    "Borough": "string",
    "Zone" : "string",
    "service_zone" : "string"
}


df = pd.read_csv(
    url,
    dtype=dtype
)

In [10]:
df.dtypes

LocationID       Int64
Borough         string
Zone            string
service_zone    string
dtype: object

In [11]:
# Create a connection to the PostgreSQL database using SQLAlchemy
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [13]:
print(pd.io.sql.get_schema(df, name='taxi_zone_lookup', con=engine))

CREATE TABLE taxi_zone_lookup (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [15]:
# just creating the schema an empty dataframe
df.head(n=0).to_sql(name='taxi_zone_lookup', con=engine, if_exists='replace')

0

In [16]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    iterator=True,
    chunksize=10)

In [19]:
df = next(df_iter)

In [20]:
df

    LocationID    Borough                     Zone service_zone
10          11   Brooklyn               Bath Beach    Boro Zone
11          12  Manhattan             Battery Park  Yellow Zone
12          13  Manhattan        Battery Park City  Yellow Zone
13          14   Brooklyn                Bay Ridge    Boro Zone
14          15     Queens  Bay Terrace/Fort Totten    Boro Zone
15          16     Queens                  Bayside    Boro Zone
16          17   Brooklyn                  Bedford    Boro Zone
17          18      Bronx             Bedford Park    Boro Zone
18          19     Queens                Bellerose    Boro Zone
19          20      Bronx                  Belmont    Boro Zone

In [21]:
from tqdm.auto import tqdm

In [22]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='taxi_zone_lookup', con=engine, if_exists='append')

0it [00:00, ?it/s]